import type { Metadata } from "next";
import { Raleway, Bebas_Neue } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/Header";
import Script from "next/script";
import TallySidebar from "@/components/TallySidebar";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("dark font-sans scroll-smooth", raleway.variable, bebasNeue.variable)}>
      <body
        className="bg-mega-black text-mega-silver antialiased selection:bg-mega-green selection:text-black overflow-x-hidden min-h-screen"
      >
        <Header />
        {children}
        <TallySidebar />
        <Script src="https://tally.so/widgets/embed.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
