import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavigationMenu from "@/components/NavigationMenu";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("dark font-sans scroll-smooth", geistSans.variable, geistMono.variable, jetbrainsMono.variable)}>
      <body
        className="bg-mega-black text-mega-silver antialiased selection:bg-mega-green selection:text-black overflow-x-hidden min-h-screen"
      >
        <NavigationMenu />
        {children}
      </body>
    </html>
  );
}
